version: "3.8"
services:
  db:
    image: postgres
    restart: always
    container_name: bronty_postgresql_container
    environment: 
      POSTGRES_PASSWORD: "${POSTGRESQL_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${DB}"
    ports:
      - "5432:5432"
    volumes: 
      - my_db:/var/lib/postgresql
  adminer:
    image: adminer
    container_name: bronty_adminer_container
    ports:
      - "8080:8080"
volumes: 
  my_db:
